import React from 'react'
import Navbar from './Navbar';
import Footer from './Footer';
import Head from 'next/head'

function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Real Estate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto">
        <Navbar />
        {children}
        <Footer />
      </div>
    </>
  )
}

export default Layout
